name: build

# this shit is ai trial and error fr

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup xmake with specified version
      - name: xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: 'latest'

      # Set the project root path and build
      - name: build
        run: |
          cd ./plugin
          xmake              

      - name: artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ehh # Name of the artifact
          path: ./plugin/dist/ # Path to the build files
          
